// Oracle OS data contracts + safe fallback.
// Real dashboard state comes from /oracleLive.json, generated by scripts/generateOracleData.mjs.

export interface OracleProject {
  name: string
  url?: string
  status: string
  note: string
  accent: 'orange' | 'cyan' | 'violet' | 'green'
}

export interface OracleLearning {
  title: string
  date: string
  summary: string
}

export interface OracleCron {
  name: string
  schedule: string
  nextRun: string
  status: string
}

export interface OracleWebsiteStatus {
  name: string
  url: string
  ok: boolean
  status: number | null
  responseMs: number | null
  checkedAt: string
  note?: string
}

export interface OracleRepoStatus {
  name: string
  path: string
  branch: string
  commit: string
  commitSubject: string
  dirty: boolean
  changedFiles: number
  lastCommitAt: string
  github?: string
  remoteHost?: string
}

export interface OracleGitHubWorkflowStatus {
  name: string
  status: string
  conclusion: string | null
  branch?: string
  event?: string
  updatedAt?: string
  url?: string
}

export interface OracleGitHubRepoStatus {
  provider: 'github'
  repo: string
  localName?: string
  apiStatus: string
  private?: boolean
  defaultBranch?: string
  pushedAt?: string
  openIssues?: number
  openPullRequests?: number
  latestWorkflow?: OracleGitHubWorkflowStatus | null
  note?: string
}

export interface OracleDeploymentStatus {
  provider: 'vercel' | 'local'
  project: string
  state: string
  url?: string
  createdAt?: string
  note?: string
}

export interface OracleCredentialStatus {
  name: string
  configured: boolean
  purpose: string
}

// ── Phase 2A types ──────────────────────────────────────────────────────────

export interface OracleIncident {
  id: string
  severity: 'critical' | 'warning' | 'info'
  category:
    | 'github-actions-failed'
    | 'website-down'
    | 'website-slow'
    | 'repo-dirty'
    | 'credential-missing'
    | 'stale-snapshot'
  project: string
  title: string
  detail: string
  detectedAt: string
  url?: string
}

export interface OracleRecommendation {
  project: string
  priority: 'high' | 'medium' | 'low'
  reason: string
  risk: 'high' | 'medium' | 'low'
  suggestedAction: string
}

export interface OracleWiroCiJobDetails {
  jobName: string
  failedStep: string | null
  failureCategory: string
}

export interface OracleWiroCi {
  repo: string
  workflowName: string
  status: string
  conclusion: string | null
  branch: string
  event?: string
  updatedAt: string
  url?: string
  failureCategory?: string | null
  jobDetails?: OracleWiroCiJobDetails | null
}

export interface OracleDeployEvent {
  provider: string
  project: string
  event: string
  state: string
  url?: string
  timestamp: string
  note?: string
}

// ── Root data contract ──────────────────────────────────────────────────────

export interface OracleData {
  generated: string
  born: string
  level3Phase: string
  stats: {
    learnings: number
    retrospectives: number
    activeProjects: number
    inboxItems: number
    writingDocs: number
    labExperiments: number
  }
  recentLearnings: OracleLearning[]
  retrospectivesCount: number
  retrospectivesRecent: string[]
  activeCrons: OracleCron[]
  projects: OracleProject[]
  websites: OracleWebsiteStatus[]
  repos: OracleRepoStatus[]
  deployments: OracleDeploymentStatus[]
  github: OracleGitHubRepoStatus[]
  credentials: OracleCredentialStatus[]
  // Phase 2A — optional so stale JSON doesn't break the UI
  incidents?: OracleIncident[]
  recommendations?: OracleRecommendation[]
  wiroCi?: OracleWiroCi | null
  deployTimeline?: OracleDeployEvent[]
  nextActions: string[]
}

export const ORACLE_FALLBACK_DATA: OracleData = {
  generated: new Date(0).toISOString(),
  born: '2026-04-18',
  level3Phase: 'Phase 2A: Better Read-only Intelligence — live JSON not generated yet',
  stats: {
    learnings: 0,
    retrospectives: 0,
    activeProjects: 0,
    inboxItems: 0,
    writingDocs: 0,
    labExperiments: 0,
  },
  recentLearnings: [],
  retrospectivesCount: 0,
  retrospectivesRecent: [],
  activeCrons: [],
  projects: [
    {
      name: 'Moshe Oracle OS',
      status: 'Building',
      note: 'Generate /oracleLive.json to activate real read-only monitoring.',
      accent: 'orange',
    },
  ],
  websites: [],
  repos: [],
  deployments: [
    {
      provider: 'local',
      project: 'Oracle Dashboard',
      state: 'needs-generate',
      note: 'Run npm run generate:oracle before build/deploy.',
    },
  ],
  github: [],
  credentials: [
    { name: 'VERCEL_TOKEN', configured: false, purpose: 'Optional Vercel read-only deploy status' },
    { name: 'GITHUB_TOKEN', configured: false, purpose: 'Optional GitHub API read-only status' },
  ],
  incidents: [],
  recommendations: [
    {
      project: 'Oracle OS',
      priority: 'low',
      reason: 'Generate live data to activate full intelligence',
      risk: 'low',
      suggestedAction: 'Run node scripts/generateOracleData.mjs to populate all sensors.',
    },
  ],
  wiroCi: null,
  deployTimeline: [],
  nextActions: [
    'Run node scripts/generateOracleData.mjs',
    'Configure fresh env tokens only if Mike wants cloud deploy status',
  ],
}
