// Oracle OS data contracts + safe fallback.
// Real dashboard state comes from /oracleLive.json, generated by scripts/generateOracleData.mjs.

export interface OracleProject {
  name: string
  url?: string
  status: string
  note: string
  accent: 'orange' | 'cyan' | 'violet' | 'green'
}

export interface OracleLearning {
  title: string
  date: string
  summary: string
}

export interface OracleCron {
  name: string
  schedule: string
  nextRun: string
  status: string
}

export interface OracleWebsiteStatus {
  name: string
  url: string
  ok: boolean
  status: number | null
  responseMs: number | null
  checkedAt: string
  note?: string
}

export interface OracleRepoStatus {
  name: string
  path: string
  branch: string
  commit: string
  commitFull: string
  commitSubject: string
  dirty: boolean
  changedFiles: number
  lastCommitAt: string
  github?: string
  remoteHost?: string
}

export interface OracleGitHubWorkflowStatus {
  name: string
  status: string
  conclusion: string | null
  branch?: string
  event?: string
  updatedAt?: string
  url?: string
}

export interface OracleGitHubRepoStatus {
  provider: 'github'
  repo: string
  localName?: string
  apiStatus: string
  private?: boolean
  defaultBranch?: string
  pushedAt?: string
  openIssues?: number
  openPullRequests?: number
  latestWorkflow?: OracleGitHubWorkflowStatus | null
  note?: string
}

export interface OracleDeploymentStatus {
  provider: 'vercel' | 'local'
  project: string
  state: string
  url?: string
  createdAt?: string
  gitCommitSha?: string
  gitCommitMessage?: string
  gitCommitRef?: string
  gitDirty?: boolean
  note?: string
}

export interface OracleCredentialStatus {
  name: string
  configured: boolean
  purpose: string
}

// ── Phase 2A types ──────────────────────────────────────────────────────────

export interface OracleIncident {
  id: string
  severity: 'critical' | 'warning' | 'info'
  category:
    | 'github-actions-failed'
    | 'website-down'
    | 'website-slow'
    | 'repo-dirty'
    | 'credential-missing'
    | 'stale-snapshot'
  project: string
  title: string
  detail: string
  detectedAt: string
  url?: string
}

export interface OracleRecommendation {
  project: string
  priority: 'high' | 'medium' | 'low'
  reason: string
  risk: 'high' | 'medium' | 'low'
  suggestedAction: string
}

export interface OracleWiroCiJobDetails {
  jobName: string
  failedStep: string | null
  failureCategory: string
}

export interface OracleWiroCi {
  repo: string
  workflowName: string
  status: string
  conclusion: string | null
  branch: string
  event?: string
  updatedAt: string
  url?: string
  failureCategory?: string | null
  jobDetails?: OracleWiroCiJobDetails | null
}

export interface OracleDeployEvent {
  provider: string
  project: string
  event: string
  state: string
  url?: string
  timestamp: string
  deployedCommitSha?: string
  deployedCommitMessage?: string
  sourceRepo?: string
  sourceCommitSha?: string
  syncState?: 'in-sync' | 'behind' | 'ahead' | 'unknown'
  note?: string
}

export interface OracleAutomationAction {
  id: string
  title: string
  description: string
  transport: 'preview-only' | 'github-api' | 'vercel-api' | 'local-script'
  risk: 'low' | 'medium' | 'high'
  requiresConfirmation: boolean
}

export interface OracleAutomationPolicy {
  enabled: boolean
  authConfigured: boolean
  sessionConfigured: boolean
  endpoint: string
  sessionEndpoint: string
  authHeader: string
  authMethod: 'preview-only' | 'signed-session-cookie'
  auditPath: string
  executionMode: 'preview-only' | 'server-enabled'
  sessionTtlMinutes: number
  note?: string
  actions: OracleAutomationAction[]
}

export interface OracleAutomationAuditEntry {
  id: string
  requestedAt: string
  actor: string
  actionId: string
  outcome: 'allowed' | 'denied' | 'preview'
  detail: string
}

export interface OracleReadinessCheck {
  label: string
  status: 'pass' | 'watch' | 'fail'
  detail: string
  weight: number
}

export interface OracleOperationalReadiness {
  score: number
  status: 'excellent' | 'steady' | 'watch' | 'critical'
  summary: string
  checks: OracleReadinessCheck[]
}

export interface OracleFeedbackSignal {
  id: string
  source: string
  businessArea: 'oracle_os' | 'wiro_growth' | 'deploy_reliability' | 'business_opportunity' | 'memory_continuity' | 'decision_load_reduction'
  actionability: 'high' | 'medium' | 'low'
  freshness: 'fresh' | 'stale' | 'unknown'
  riskLevel: 'low' | 'medium' | 'high'
  approvalRequired: boolean
  mikeFeedback: 'useful' | 'noisy' | 'missing-context' | 'unrated'
  valueSignal: string
}

export interface OracleFeedbackLedger {
  updatedAt: string
  summary: string
  signals: OracleFeedbackSignal[]
  counts: {
    useful: number
    noisy: number
    unrated: number
    highActionability: number
    approvalRequired: number
  }
  nextLearningStep: string
}

export interface OracleRepoHygieneItem {
  repo: string
  branch: string
  changedFiles: number
  untrackedFiles: number
  protectedTouched: boolean
  verdict: 'clean' | 'review' | 'blocked'
  recommendation: string
}

export interface OracleRepoHygiene {
  updatedAt: string
  verdict: 'clean' | 'review' | 'blocked'
  summary: string
  items: OracleRepoHygieneItem[]
}

export interface OracleDeploymentFreshnessGap {
  updatedAt: string
  verdict: 'in_sync' | 'review_before_ship' | 'approval_required' | 'unknown'
  summary: string
  liveProject: string
  liveCommit?: string
  localCommit?: string
  snapshotAgeMinutes: number
  worktreeDirty: boolean
  dirtyRepoCount: number
  recommendation: string
}

export interface OraclePhase5ALayer {
  updatedAt: string
  phase: 'phase_5a'
  summary: string
  feedbackLedger: OracleFeedbackLedger
  repoHygiene: OracleRepoHygiene
  deploymentFreshnessGap: OracleDeploymentFreshnessGap
  phase5BRequirements: string[]
}


export interface OracleMikeFeedbackEntry {
  id: string
  signalId: string
  rating: 'useful' | 'noisy' | 'missing-context' | 'action-taken' | 'ignored'
  note: string
  source: 'dashboard' | 'telegram' | 'api' | 'imported'
  actor: string
  createdAt: string
}

export interface OracleEvidenceChain {
  id: string
  target: string
  status: 'complete' | 'partial' | 'missing'
  summary: string
  proofs: string[]
  missing: string[]
  rollbackNote: string
}

export interface OracleSafeExecutorQueueItem {
  id: string
  title: string
  autonomyLevel: 'safe_now'
  status: 'ready' | 'blocked' | 'running' | 'completed'
  businessArea: string
  evidenceChainId: string
  rollbackNote: string
  guardrail: string
  nextStep: string
}

export interface OracleApprovalInboxItem {
  id: string
  title: string
  state: 'pending' | 'approved' | 'rejected' | 'deferred' | 'expired'
  risk: 'low' | 'medium' | 'high'
  requestedAction: string
  approvalTrigger: string
  evidenceChainId?: string
  expiresAt?: string
}

export interface OracleBusinessValueScore {
  area: string
  score: number
  verdict: 'promote' | 'watch' | 'suppress'
  reason: string
  noisePenalty: number
}

export interface OraclePhase5BLayer {
  updatedAt: string
  phase: 'phase_5b'
  summary: string
  feedbackPersistence: {
    endpoint: string
    configured: boolean
    pathLabel: string
    entries: OracleMikeFeedbackEntry[]
    counts: {
      useful: number
      noisy: number
      missingContext: number
      actionTaken: number
      ignored: number
    }
    nextLearningStep: string
  }
  evidenceChains: OracleEvidenceChain[]
  safeExecutorQueue: OracleSafeExecutorQueueItem[]
  approvalInbox: OracleApprovalInboxItem[]
  businessValueScores: OracleBusinessValueScore[]
  guardrails: string[]
  phase5CRequirements: string[]
}


export interface OracleExecutorRun {
  id: string
  queueItemId: string
  actionId: string
  state: 'started' | 'completed' | 'failed' | 'skipped'
  actor: string
  startedAt: string
  completedAt?: string
  durationMs?: number
  exitCode?: number
  summary: string
  rollbackNote: string
}

export interface OracleSafePromotionCandidate {
  id: string
  queueItemId: string
  status: 'eligible' | 'blocked' | 'watch'
  cadence: string
  reason: string
  requiredEvidence: string[]
}

export interface OracleTelegramApprovalPayload {
  id: string
  approvalInboxId: string
  message: string
  actions: ('approve' | 'reject' | 'defer')[]
  expiresAt?: string
}

export interface OracleLiveSmokeCheck {
  label: string
  status: 'pass' | 'watch' | 'fail'
  detail: string
}

export interface OraclePhase5CLayer {
  updatedAt: string
  phase: 'phase_5c'
  summary: string
  feedbackButtons: {
    enabled: boolean
    endpoint: string
    ratings: string[]
    status: 'wired' | 'locked' | 'preview'
  }
  executorRuns: {
    endpoint: string
    configured: boolean
    pathLabel: string
    runs: OracleExecutorRun[]
    counts: {
      started: number
      completed: number
      failed: number
      skipped: number
    }
  }
  promotionCandidates: OracleSafePromotionCandidate[]
  telegramApprovalPayloads: OracleTelegramApprovalPayload[]
  liveSmokeReadiness: {
    status: 'pass' | 'watch' | 'fail'
    checks: OracleLiveSmokeCheck[]
    nextStep: string
  }
  topPhaseRequirements: string[]
}


export interface OracleApprovalDecision {
  id: string
  approvalInboxId: string
  decision: 'approved' | 'rejected' | 'deferred' | 'expired'
  actor: string
  source: 'dashboard' | 'telegram' | 'api'
  note: string
  createdAt: string
}

export interface OracleCronPromotionPlan {
  id: string
  queueItemId: string
  status: 'drafted' | 'eligible' | 'blocked'
  schedule: string
  prompt: string
  guardrails: string[]
  reason: string
}

export interface OracleRepoHygieneClassification {
  repo: string
  verdict: 'source_change' | 'scratch_only' | 'docs_only' | 'mixed' | 'clean'
  trackedChanges: number
  scratchUntracked: number
  docUntracked: number
  sourceUntracked: number
  note: string
}

export interface OracleDeploySmokeGate {
  id: string
  status: 'pass' | 'watch' | 'fail'
  command: string
  expected: string
  lastObserved: string
}

export interface OraclePhase5DLayer {
  updatedAt: string
  phase: 'phase_5d'
  summary: string
  approvalCallbacks: {
    endpoint: string
    configured: boolean
    pathLabel: string
    decisions: OracleApprovalDecision[]
    counts: {
      approved: number
      rejected: number
      deferred: number
      expired: number
    }
  }
  cronPromotionPlans: OracleCronPromotionPlan[]
  repoHygieneClassifications: OracleRepoHygieneClassification[]
  deploySmokeGates: OracleDeploySmokeGate[]
  topPhaseReadiness: {
    status: 'blocked' | 'watch' | 'ready'
    blockers: string[]
    watchItems: string[]
    nextStep: string
  }
}



export interface OracleQualityRubricScore {
  id: string
  label: string
  score: number
  evidence: string
  decision: 'send' | 'test_manually' | 'keep_watching' | 'ignore'
}

export interface OracleTasteFilterRule {
  id: string
  pattern: string
  action: 'downrank' | 'suppress' | 'rewrite'
  reason: string
  source: string
}

export interface OracleWiroSignalCandidate {
  id: string
  title: string
  observedFact: string
  hypothesis: string
  tinyTest: string
  decision: 'test_manually' | 'keep_watching' | 'ignore'
  score: number
  risk: 'low' | 'medium'
}

export interface OracleApprovalUxOption {
  label: string
  decision: 'approve_once' | 'draft_only' | 'not_useful' | 'ask_later'
  effect: string
}

export interface OraclePhase5ELayer {
  updatedAt: string
  phase: 'phase_5e'
  summary: string
  qualityRubric: {
    status: 'active'
    minimumSendScore: number
    annoyanceLimit: number
    scores: OracleQualityRubricScore[]
  }
  tasteFilters: {
    status: 'active'
    rules: OracleTasteFilterRule[]
    suppressedPhrases: string[]
    lastCorrection: string
  }
  wiroFirstOpportunityFilter: {
    status: 'active'
    candidates: OracleWiroSignalCandidate[]
    rule: string
  }
  approvalUx: {
    status: 'drafted' | 'ready'
    template: string
    options: OracleApprovalUxOption[]
  }
  safeExecutorPilot: {
    status: 'ready' | 'watch' | 'blocked'
    actionId: string
    whySafe: string
    requiredBeforeTopPhase: string[]
  }
  mikeNeedsNow: {
    status: 'quiet' | 'ask' | 'act'
    headline: string
    bullets: string[]
  }
}



export interface OracleLearningMemoryRule {
  id: string
  signal: string
  learnedPreference: string
  appliedTo: string[]
  confidence: 'low' | 'medium' | 'high'
}

export interface OracleReportQualityGate {
  id: string
  label: string
  status: 'pass' | 'watch' | 'fail'
  rule: string
  evidence: string
}

export interface OracleSafePilotEvidence {
  actionId: string
  status: 'missing' | 'ready' | 'completed' | 'failed'
  latestRunId?: string
  evidence: string
  nextStep: string
}

export interface OraclePhase5FLayer {
  updatedAt: string
  phase: 'phase_5f'
  summary: string
  learningActionMemory: {
    status: 'active'
    rules: OracleLearningMemoryRule[]
    sourceCounts: {
      feedbackEntries: number
      approvalDecisions: number
      executorRuns: number
    }
  }
  reportQualityGates: OracleReportQualityGate[]
  safePilotEvidence: OracleSafePilotEvidence
  cronQualityCompliance: {
    status: 'pass' | 'watch' | 'fail'
    checkedJobs: number
    notes: string[]
  }
  topPhaseGate: {
    status: 'blocked' | 'watch' | 'ready'
    blockers: string[]
    watchItems: string[]
    nextStep: string
  }
}



export interface OracleBoundedSafeCronControl {
  id: string
  label: string
  status: 'pass' | 'watch' | 'fail'
  rule: string
  evidence: string
}

export interface OracleSafeCronPilotPlan {
  id: string
  status: 'draft_only' | 'ready' | 'blocked'
  schedule: string
  actionId: string
  maxRuns: number
  toolBudget: string
  allowedScope: string[]
  forbiddenScope: string[]
  delivery: 'origin' | 'local'
  rollback: string
}

export interface OraclePhase5GLayer {
  updatedAt: string
  phase: 'phase_5g'
  summary: string
  safeCronPilot: OracleSafeCronPilotPlan
  preflightControls: OracleBoundedSafeCronControl[]
  evidence: {
    safeExecutorPilotCompleted: boolean
    reportQualityGatesPassing: number
    reportQualityGatesTotal: number
    cronQualityStatus: 'pass' | 'watch' | 'fail'
    sourceBlockers: string[]
  }
  topPhaseGate: {
    status: 'blocked' | 'watch' | 'ready'
    blockers: string[]
    watchItems: string[]
    nextStep: string
  }
}



export interface OracleMissingFeatureRoadmapItem {
  id: 'oracle-v2-mcp' | 'oracle-studio' | 'maw-js' | 'consciousness-loop'
  label: string
  status: 'missing' | 'blocked' | 'ready_to_debug' | 'planned'
  priority: number
  dependency?: string
  command?: string
  whyItMatters: string
  nextStep: string
  safetyLane: 'safe_now' | 'draft_only' | 'approval_required'
}

export interface OraclePhase5HLayer {
  updatedAt: string
  phase: 'phase_5h'
  summary: string
  missingFeatureRoadmap: OracleMissingFeatureRoadmapItem[]
  dependencyOrder: string[]
  nextEngineeringStep: {
    id: string
    title: string
    lane: 'safe_now' | 'draft_only' | 'approval_required'
    reason: string
    commandHints: string[]
  }
  guardrails: string[]
}


export interface OracleConsciousnessCycleStep {
  id: 'sense' | 'reflect' | 'wonder' | 'decide' | 'propose' | 'remember'
  label: string
  cadence: string
  lane: 'safe_now' | 'draft_only' | 'approval_required'
  does: string
  evidenceSource: string
  output: string
  guardrail: string
}

export interface OracleConsciousnessSignal {
  id: string
  label: string
  status: 'live' | 'watch' | 'missing'
  source: string
  whyItMatters: string
}

export interface OracleConsciousnessBoundary {
  rule: string
  lane: 'safe_now' | 'draft_only' | 'approval_required'
  reason: string
}

export interface OraclePhase5ILayer {
  updatedAt: string
  phase: 'phase_5i'
  summary: string
  definition: string
  operatingMode: 'bounded_consciousness_loop'
  status: 'draft_ready' | 'watch' | 'blocked'
  loop: OracleConsciousnessCycleStep[]
  signals: OracleConsciousnessSignal[]
  boundaries: OracleConsciousnessBoundary[]
  dailyReflection: {
    status: 'draft_ready' | 'watch' | 'blocked'
    prompt: string
    outputPath: string
    maxFrequency: string
    delivery: 'local' | 'origin'
  }
  nextThought: {
    title: string
    lane: 'safe_now' | 'draft_only' | 'approval_required'
    why: string
    safeAction: string
  }
  topPhaseGate: {
    status: 'blocked' | 'watch' | 'ready'
    blockers: string[]
    watchItems: string[]
    nextStep: string
  }
}


export interface OraclePhase5JMcpCheck {
  id: string
  label: string
  status: 'pass' | 'watch' | 'fail'
  evidence: string
}

export interface OraclePhase5JLayer {
  updatedAt: string
  phase: 'phase_5j'
  summary: string
  status: 'connected' | 'watch' | 'blocked'
  rootCause: string
  server: {
    package: string
    url: string
    healthEndpoint: string
    version?: string
    status: 'ok' | 'watch' | 'fail'
  }
  adapter: {
    path: string
    transport: 'stdio-json-lines'
    tools: string[]
    autostart: boolean
    status: 'ready' | 'watch' | 'fail'
  }
  hermesConfig: {
    configured: boolean
    serverName: string
    restartRequired: boolean
    configPath: string
  }
  checks: OraclePhase5JMcpCheck[]
  nextStep: string
}

export interface OracleTodayLearning {
  title: string
  source: string
  date: string
  insight: string
  whyItMatters: string
  nextAction: string
}

export interface OracleOpportunityRadarItem {
  rank: number
  title: string
  score: number
  fit: 'excellent' | 'strong' | 'watch'
  thesis: string
  pricing: string
  validationStep: string
  source: string
}

export interface OracleApprovalQueueItem {
  id?: string
  title: string
  category: 'safe' | 'draft-only' | 'approval-required'
  autonomyLevel?: 'safe_now' | 'draft_only' | 'approval_required'
  businessArea?: 'oracle_os' | 'wiro_growth' | 'deploy_reliability' | 'business_opportunity' | 'memory_continuity' | 'customer_or_public'
  risk: 'low' | 'medium' | 'high'
  riskReason?: string
  reason: string
  proposedAction: string
  nextSafeStep?: string
  approvalTrigger?: string
  source: string
}

export interface OracleAutonomyRouterLane {
  id: 'safe_now' | 'draft_only' | 'approval_required'
  label: string
  status: 'active' | 'guarded' | 'locked'
  summary: string
  examples: string[]
  count: number
  canExecute: boolean
  allowedWork: string[]
  blockedWork: string[]
}

export interface OracleAutonomyRouterDecision {
  id: string
  title: string
  autonomyLevel: 'safe_now' | 'draft_only' | 'approval_required'
  businessArea: string
  risk: 'low' | 'medium' | 'high'
  riskReason: string
  nextSafeStep: string
  approvalTrigger: string
  source: string
}

export interface OracleAutonomyRouter {
  updatedAt: string
  phase: 'phase_4'
  summary: string
  lanes: OracleAutonomyRouterLane[]
  decisions: OracleAutonomyRouterDecision[]
  guardrails: string[]
  phase5Requirements: string[]
}

export interface OracleTerminalPolicy {
  enabled: boolean
  terminalEnabled: boolean
  sessionConfigured: boolean
  endpoint: string
  authMethod: 'preview-only' | 'signed-session-cookie'
  defaultCwd: string
  allowedCwdPrefixes: string[]
  note: string
}

export interface OracleIntelligenceLayer {
  updatedAt: string
  summary: string
  todayLearnings: OracleTodayLearning[]
  opportunityRadar: OracleOpportunityRadarItem[]
  approvalQueue: OracleApprovalQueueItem[]
  autonomyRouter: OracleAutonomyRouter
}

// ── Root data contract ──────────────────────────────────────────────────────

export interface OracleData {
  generated: string
  born: string
  level3Phase: string
  stats: {
    learnings: number
    retrospectives: number
    activeProjects: number
    inboxItems: number
    writingDocs: number
    labExperiments: number
  }
  recentLearnings: OracleLearning[]
  retrospectivesCount: number
  retrospectivesRecent: string[]
  activeCrons: OracleCron[]
  projects: OracleProject[]
  websites: OracleWebsiteStatus[]
  repos: OracleRepoStatus[]
  deployments: OracleDeploymentStatus[]
  github: OracleGitHubRepoStatus[]
  credentials: OracleCredentialStatus[]
  // Phase 2A — optional so stale JSON doesn't break the UI
  incidents?: OracleIncident[]
  recommendations?: OracleRecommendation[]
  wiroCi?: OracleWiroCi | null
  deployTimeline?: OracleDeployEvent[]
  automation?: OracleAutomationPolicy | null
  operationalReadiness?: OracleOperationalReadiness
  intelligenceLayer?: OracleIntelligenceLayer
  terminal?: OracleTerminalPolicy
  phase5A?: OraclePhase5ALayer
  phase5B?: OraclePhase5BLayer
  phase5C?: OraclePhase5CLayer
  phase5D?: OraclePhase5DLayer
  phase5E?: OraclePhase5ELayer
  phase5F?: OraclePhase5FLayer
  phase5G?: OraclePhase5GLayer
  phase5H?: OraclePhase5HLayer
  phase5I?: OraclePhase5ILayer
  phase5J?: OraclePhase5JLayer
  nextActions: string[]
}

export const ORACLE_FALLBACK_DATA: OracleData = {
  generated: new Date(0).toISOString(),
  born: '2026-04-18',
  level3Phase: 'Phase 2A: Better Read-only Intelligence — live JSON not generated yet',
  stats: {
    learnings: 0,
    retrospectives: 0,
    activeProjects: 0,
    inboxItems: 0,
    writingDocs: 0,
    labExperiments: 0,
  },
  recentLearnings: [],
  retrospectivesCount: 0,
  retrospectivesRecent: [],
  activeCrons: [],
  projects: [
    {
      name: 'Moshe Oracle OS',
      status: 'Building',
      note: 'Generate /oracleLive.json to activate real read-only monitoring.',
      accent: 'orange',
    },
  ],
  websites: [],
  repos: [],
  deployments: [
    {
      provider: 'local',
      project: 'Oracle Dashboard',
      state: 'needs-generate',
      note: 'Run npm run generate:oracle before build/deploy.',
    },
  ],
  github: [],
  credentials: [
    { name: 'VERCEL_TOKEN', configured: false, purpose: 'Optional Vercel read-only deploy status' },
    { name: 'GITHUB_TOKEN', configured: false, purpose: 'Optional GitHub API read-only status' },
  ],
  incidents: [],
  recommendations: [
    {
      project: 'Oracle OS',
      priority: 'low',
      reason: 'Generate live data to activate full intelligence',
      risk: 'low',
      suggestedAction: 'Run node scripts/generateOracleData.mjs to populate all sensors.',
    },
  ],
  wiroCi: null,
  deployTimeline: [],
  automation: {
    enabled: false,
    authConfigured: false,
    sessionConfigured: false,
    endpoint: '/api/oracle/actions',
    sessionEndpoint: '/api/oracle/session',
    authHeader: 'HttpOnly signed session cookie',
    authMethod: 'preview-only',
    auditPath: '/tmp/oracle-action-audit.jsonl',
    executionMode: 'preview-only',
    sessionTtlMinutes: 480,
    note: 'Preview trigger is wired to the action API path. Set ORACLE_SESSION_SECRET to arm Mike-only session-gated execution.',
    actions: [
      {
        id: 'refresh-oracle-snapshot',
        title: 'Refresh Oracle snapshot',
        description: 'Regenerate the read-only Oracle data bundle and re-evaluate sensors.',
        transport: 'local-script',
        risk: 'low',
        requiresConfirmation: true,
      },
      {
        id: 'dispatch-wiro-ci',
        title: 'Dispatch Wiro CI',
        description: 'Trigger the allowlisted GitHub workflow that verifies Wiro4x4 health.',
        transport: 'github-api',
        risk: 'medium',
        requiresConfirmation: true,
      },
      {
        id: 'vercel-redeploy',
        title: 'Request Vercel redeploy',
        description: 'Ask Vercel to redeploy the Oracle dashboard after a confirmed change.',
        transport: 'vercel-api',
        risk: 'medium',
        requiresConfirmation: true,
      },
    ],
  },
  operationalReadiness: {
    score: 0,
    status: 'watch',
    summary: 'Waiting for the first live Oracle readiness snapshot.',
    checks: [],
  },
  intelligenceLayer: {
    updatedAt: new Date(0).toISOString(),
    summary: 'Waiting for the first Oracle intelligence snapshot.',
    todayLearnings: [],
    opportunityRadar: [],
    approvalQueue: [],
    autonomyRouter: {
      updatedAt: new Date(0).toISOString(),
      phase: 'phase_4',
      summary: 'Waiting for the first autonomy router snapshot.',
      lanes: [],
      decisions: [],
      guardrails: [],
      phase5Requirements: [],
    },
  },
  terminal: {
    enabled: false,
    terminalEnabled: false,
    sessionConfigured: false,
    endpoint: '/api/oracle/terminal',
    authMethod: 'preview-only',
    defaultCwd: '/Users/pasuthunjunkong/workspace/Moshe',
    allowedCwdPrefixes: ['/Users/pasuthunjunkong/workspace/Moshe'],
    note: 'Terminal execution is disabled until the local/admin runtime explicitly enables it.',
  },
  phase5A: {
    updatedAt: new Date(0).toISOString(),
    phase: 'phase_5a',
    summary: 'Waiting for Phase 5A closed-loop sensors.',
    feedbackLedger: {
      updatedAt: new Date(0).toISOString(),
      summary: 'No signal quality ledger generated yet.',
      signals: [],
      counts: { useful: 0, noisy: 0, unrated: 0, highActionability: 0, approvalRequired: 0 },
      nextLearningStep: 'Generate oracleLive.json to collect feedback signals.',
    },
    repoHygiene: {
      updatedAt: new Date(0).toISOString(),
      verdict: 'review',
      summary: 'No repo hygiene snapshot generated yet.',
      items: [],
    },
    deploymentFreshnessGap: {
      updatedAt: new Date(0).toISOString(),
      verdict: 'unknown',
      summary: 'No deployment freshness gap snapshot generated yet.',
      liveProject: 'unknown',
      snapshotAgeMinutes: 0,
      worktreeDirty: false,
      dirtyRepoCount: 0,
      recommendation: 'Generate oracleLive.json to compare live deploy and local state.',
    },
    phase5BRequirements: [],
  },
  phase5B: {
    updatedAt: new Date(0).toISOString(),
    phase: 'phase_5b',
    summary: 'Waiting for Phase 5B feedback persistence and safe-executor queue.',
    feedbackPersistence: {
      endpoint: '/api/oracle/feedback',
      configured: false,
      pathLabel: 'not configured',
      entries: [],
      counts: { useful: 0, noisy: 0, missingContext: 0, actionTaken: 0, ignored: 0 },
      nextLearningStep: 'Unlock the Mike session gate and record feedback on a signal.',
    },
    evidenceChains: [],
    safeExecutorQueue: [],
    approvalInbox: [],
    businessValueScores: [],
    guardrails: [],
    phase5CRequirements: [],
  },
  phase5C: {
    updatedAt: new Date(0).toISOString(),
    phase: 'phase_5c',
    summary: 'Waiting for Phase 5C autonomous run-state loop.',
    feedbackButtons: { enabled: false, endpoint: '/api/oracle/feedback', ratings: [], status: 'preview' },
    executorRuns: {
      endpoint: '/api/oracle/executor',
      configured: false,
      pathLabel: 'not configured',
      runs: [],
      counts: { started: 0, completed: 0, failed: 0, skipped: 0 },
    },
    promotionCandidates: [],
    telegramApprovalPayloads: [],
    liveSmokeReadiness: { status: 'watch', checks: [], nextStep: 'Generate a fresh Oracle snapshot.' },
    topPhaseRequirements: [],
  },
  phase5D: {
    updatedAt: new Date(0).toISOString(),
    phase: 'phase_5d',
    summary: 'Waiting for Phase 5D approval callbacks and cron promotion gates.',
    approvalCallbacks: {
      endpoint: '/api/oracle/approval',
      configured: false,
      pathLabel: 'not configured',
      decisions: [],
      counts: { approved: 0, rejected: 0, deferred: 0, expired: 0 },
    },
    cronPromotionPlans: [],
    repoHygieneClassifications: [],
    deploySmokeGates: [],
    topPhaseReadiness: { status: 'blocked', blockers: ['Generate a fresh Oracle snapshot.'], watchItems: [], nextStep: 'Run npm run build.' },
  },
  phase5E: {
    updatedAt: new Date(0).toISOString(),
    phase: 'phase_5e',
    summary: 'Waiting for Phase 5E quality intelligence.',
    qualityRubric: { status: 'active', minimumSendScore: 18, annoyanceLimit: 2, scores: [] },
    tasteFilters: { status: 'active', rules: [], suppressedPhrases: [], lastCorrection: 'No correction loaded yet.' },
    wiroFirstOpportunityFilter: { status: 'active', candidates: [], rule: 'Prefer Wiro-backed observed facts over generic opportunity ideas.' },
    approvalUx: { status: 'drafted', template: 'What this does / Risk / Rollback / Why now', options: [] },
    safeExecutorPilot: { status: 'watch', actionId: 'queue-refresh-oracle-snapshot', whySafe: 'Internal snapshot refresh only.', requiredBeforeTopPhase: [] },
    mikeNeedsNow: { status: 'quiet', headline: 'Generate a fresh Oracle snapshot.', bullets: [] },
  },
  phase5F: {
    updatedAt: new Date(0).toISOString(),
    phase: 'phase_5f',
    summary: 'Waiting for Phase 5F learning action memory.',
    learningActionMemory: { status: 'active', rules: [], sourceCounts: { feedbackEntries: 0, approvalDecisions: 0, executorRuns: 0 } },
    reportQualityGates: [],
    safePilotEvidence: { actionId: 'queue-refresh-oracle-snapshot', status: 'missing', evidence: 'No live snapshot generated yet.', nextStep: 'Generate a fresh Oracle snapshot.' },
    cronQualityCompliance: { status: 'watch', checkedJobs: 0, notes: [] },
    topPhaseGate: { status: 'blocked', blockers: ['Generate a fresh Oracle snapshot.'], watchItems: [], nextStep: 'Run npm run build.' },
  },
  phase5G: {
    updatedAt: new Date(0).toISOString(),
    phase: 'phase_5g',
    summary: 'Waiting for Phase 5G bounded safe cron pilot.',
    safeCronPilot: { id: 'bounded-safe-now-refresh-pilot', status: 'draft_only', schedule: 'manual only', actionId: 'queue-refresh-oracle-snapshot', maxRuns: 0, toolBudget: 'none', allowedScope: [], forbiddenScope: [], delivery: 'local', rollback: 'Do not schedule until snapshot is generated.' },
    preflightControls: [],
    evidence: { safeExecutorPilotCompleted: false, reportQualityGatesPassing: 0, reportQualityGatesTotal: 0, cronQualityStatus: 'watch', sourceBlockers: [] },
    topPhaseGate: { status: 'blocked', blockers: ['Generate a fresh Oracle snapshot.'], watchItems: [], nextStep: 'Run npm run build.' },
  },
  phase5H: {
    updatedAt: new Date(0).toISOString(),
    phase: 'phase_5h',
    summary: 'Waiting for Phase 5H integration roadmap.',
    missingFeatureRoadmap: [],
    dependencyOrder: [],
    nextEngineeringStep: { id: 'none', title: 'Generate a fresh Oracle snapshot.', lane: 'safe_now', reason: 'No roadmap snapshot exists yet.', commandHints: [] },
    guardrails: [],
  },
  phase5I: {
    updatedAt: new Date(0).toISOString(),
    phase: 'phase_5i',
    summary: 'Waiting for Phase 5I Consciousness Loop.',
    definition: 'Operational consciousness means a bounded sense-reflect-decide-remember loop, not human sentience.',
    operatingMode: 'bounded_consciousness_loop',
    status: 'blocked',
    loop: [],
    signals: [],
    boundaries: [],
    dailyReflection: { status: 'blocked', prompt: 'Generate a fresh Oracle snapshot.', outputPath: 'ψ/memory/reflections/', maxFrequency: 'manual', delivery: 'local' },
    nextThought: { title: 'Generate a fresh Oracle snapshot.', lane: 'safe_now', why: 'No live consciousness snapshot exists yet.', safeAction: 'Run npm run build.' },
    topPhaseGate: { status: 'blocked', blockers: ['Generate a fresh Oracle snapshot.'], watchItems: [], nextStep: 'Run npm run build.' },
  },
  phase5J: {
    updatedAt: new Date(0).toISOString(),
    phase: 'phase_5j',
    summary: 'Waiting for Phase 5J Arra Oracle MCP connection.',
    status: 'blocked',
    rootCause: 'No live MCP readiness snapshot exists yet.',
    server: { package: 'arra-oracle@github:Soul-Brews-Studio/arra-oracle#main', url: 'http://127.0.0.1:47778', healthEndpoint: '/api/health', status: 'watch' },
    adapter: { path: 'galaxy/scripts/arraOracleMcpAdapter.mjs', transport: 'stdio-json-lines', tools: [], autostart: false, status: 'watch' },
    hermesConfig: { configured: false, serverName: 'arra_oracle', restartRequired: true, configPath: '~/.hermes/config.yaml' },
    checks: [],
    nextStep: 'Run npm run build.',
  },
  nextActions: [
    'Run node scripts/generateOracleData.mjs',
    'Configure fresh env tokens only if Mike wants cloud deploy status',
  ],
}
